### ISSUE TITLE
RootProject with relative base throws exception in Windows

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#105]
To reproduce: given projects A and B in sibling folders a and b, with B an external dependancy of A, having something like 

``` scala
val dep = RootProject( file( "../b" ) )
```

in the build config of A will throw an exception (reproduced below). I think this is because, in case of a relative path, IO.toURI passes the output of File.getPath to the URI constructor. Unfortunately, on Windows,  the string returned by getPath contains backslashes (regardless of how the original path string was specified above) and the URI constructor does not like this. 

Workaround was 

``` scala
val dep = ProjectRef( uri( "../b"), "B" )
```

at which point I lost motivation to find a fix. 

Running sbt 0.10 (not nightly), scala 2.9.0-1, jvm 6u26 (64 bit), Windows 7 (64 bit). The full exception:

Caused by: java.net.URISyntaxException: Illegal character in path at index 2: ..\sbtdemo5
        at java.net.URI$Parser.fail(URI.java:2809)
        at java.net.URI$Parser.checkChars(URI.java:2982)
        at java.net.URI$Parser.parseHierarchical(URI.java:3066)
        at java.net.URI$Parser.parse(URI.java:3024)
        at java.net.URI.<init>(URI.java:578)
        at sbt.IO$.toURI(IO.scala:616)
        at sbt.RootProject$.apply(Reference.scala:31)
        at CCPBuild$.<init>(Build.scala:40)
        at CCPBuild$.<clinit>(Build.scala)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:247)
        at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:10)
        at sbt.Load$.loadDefinition(Load.scala:364)
        at sbt.Load$$anonfun$loadDefinitions$1.apply(Load.scala:362)
        at sbt.Load$$anonfun$loadDefinitions$1.apply(Load.scala:362)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
        at scala.collection.immutable.List.map(List.scala:45)
        at sbt.Load$.loadDefinitions(Load.scala:362)
        at sbt.Load$.definitions(Load.scala:357)
        at sbt.Load$.loadUnit(Load.scala:327)
        at sbt.Load$$anonfun$5.apply(Load.scala:172)
        at sbt.Load$$anonfun$5.apply(Load.scala:172)
        at sbt.BuildLoader.apply(BuildLoader.scala:17)
        at sbt.Load$.loadAll(Load.scala:224)
        at sbt.Load$.loadURI(Load.scala:181)
        at sbt.Load$.load(Load.scala:177)
        at sbt.Load$.load(Load.scala:175)
        at sbt.Load$.apply(Load.scala:83)
        at sbt.Load$.defaultLoad(Load.scala:41)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:371)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:368)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
        at sbt.Command$.process(Command.scala:91)
        at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:72)
        at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:72)
        at sbt.State$$anon$1.process(State.scala:54)
        at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:72)
        at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:72)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
        at sbt.MainLoop$.next(Main.scala:72)
        at sbt.MainLoop$.run(Main.scala:63)
        at sbt.xMain.run(Main.scala:33)
        at xsbt.boot.Launch$.run(Launch.scala:54)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
        at xsbt.boot.Launch$.launch(Launch.scala:68)
        at xsbt.boot.Launch$.apply(Launch.scala:14)
        at xsbt.boot.Boot$.runImpl(Boot.scala:24)
        at xsbt.boot.Boot$.main(Boot.scala:15)
        at xsbt.boot.Boot.main(Boot.scala)

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#105](https://github.com/sbt/sbt/issues/105) for the full issue and to comment.
