### ISSUE TITLE
Scala REPL fails with IncompatibleClassChangeError when sbt-launch.jar is in %SCALA_HOME%/lib

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#218]
I installed the latest typesafe stack and then downloaded the sbt-launch.jar into the %SCALA_HOME%/lib.  REPL fails to run
Exception in thread "main" java.lang.IncompatibleClassChangeError: Expecting non-static method scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/m
utable/ArrayOps;
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:33)

```
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

When that jar is deleted REPL runs fine.
How do I fix this?

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#218](https://github.com/sbt/sbt/issues/218) for the full issue and to comment.
