### ISSUE TITLE
"java.io.IOException: Broken pipe" after foo!< and a key stroke

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#327]
## steps
1. From sbt shell:
   
   ```
   > set TaskKey[Int]("rmtest") := { "rm -i test.txt"!< }
   > rmtest
   rm: test.txt: No such file or directory
   [success] Total time: 0 s, completed Jan 8, 2012 12:39:52 PM
   ```
2. Then hit enter.
## problem

```
> Exception in thread "Thread-66" java.io.IOException: Broken pipe
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:282)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
    at sbt.BasicIO$.read$1(ProcessImpl.scala:108)
    at sbt.BasicIO$.transferFullyImpl(ProcessImpl.scala:112)
    at sbt.BasicIO$.transferFully(ProcessImpl.scala:88)
    at sbt.BasicIO$.connectToIn(ProcessImpl.scala:79)
    at sbt.BasicIO$$anonfun$input$1.apply(ProcessImpl.scala:80)
    at sbt.BasicIO$$anonfun$input$1.apply(ProcessImpl.scala:80)
    at sbt.SimpleProcessBuilder$$anonfun$2.apply$mcV$sp(ProcessImpl.scala:383)
    at sbt.Spawn$$anon$3.run(ProcessImpl.scala:20)
```
## expectation

No error. (It seems like the character is sent to the already-closed process)
## note

This is a minimal repro of a bug reported to sbt-appengine, which spawns `appcfg.sh`.

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#327](https://github.com/sbt/sbt/issues/327) for the full issue and to comment.
