### ISSUE TITLE
API phase too eager when computing dependencies on binary types

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#417]
Using 0.11.2.

I have the following crash in the build compiler inside Eclipse. It basically complains about a type not being on my classpath. I think it needn't be, since it's referenced from a classfile on my classpath (that I don't use). The dependency graph is:

my project -> sdt.core -> org.eclipse.jface

on my classpath I have only sdt.core.jar. 

Since the typer succeeded, it means that type wasn't needed for compilation. I wonder if the API phase could skip types that have not been yet completed (so, never force a lazy type).

```
scala.reflect.internal.Types$TypeError: while unpickling /Users/dragos/workspace/git/plugin/dragos-scala-ide/org.scala ide.sdt.core/target/classes/scala/tools/eclipse/javaelements/ScalaOverrideIndicatorBuilder.class, reference value jface of package org.eclipse/List(package eclipse, package org, package <root>)/
   package jdt not found.
at scala.reflect.internal.pickling.UnPickler$Scan.toTypeError(UnPickler.scala:842)
at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:855)
at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.load(UnPickler.scala:857)
at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1218)
at xsbt.API.typeParameters(API.scala:323)
at xsbt.API.xsbt$API$$mkClassLike(API.scala:354)
at xsbt.API$$anonfun$xsbt$API$$classLike$1.apply(API.scala:340)
at xsbt.API$$anonfun$xsbt$API$$classLike$1.apply(API.scala:340)
at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:169)
at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
at xsbt.API.xsbt$API$$classLike(API.scala:340)
at xsbt.API.xsbt$API$$definition(API.scala:250)
at xsbt.API$$anonfun$xsbt$API$$processDefinitions$1.apply(API.scala:244)
at xsbt.API$$anonfun$xsbt$API$$processDefinitions$1.apply(API.scala:244)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:247)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:247)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:247)
at scala.collection.mutable.ArrayOps.flatMap(ArrayOps.scala:38)
at xsbt.API.xsbt$API$$processDefinitions(API.scala:244)
at xsbt.API$$anonfun$mkStructure$3.apply(API.scala:242)
at xsbt.API$$anonfun$mkStructure$3.apply(API.scala:242)
at xsbt.Message$$anon$1.apply(Message.scala:8)
at xsbti.SafeLazy$$anonfun$apply$1.apply(SafeLazy.scala:8)
at xsbti.SafeLazy$Impl._t(SafeLazy.scala:20)
at xsbti.SafeLazy$Impl.get(SafeLazy.scala:24)
at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:94)
at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:94)
at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
at scala.collection.immutable.List.foreach(List.scala:77)
at xsbt.API.xsbt$API$$forceStructures(API.scala:94)
at xsbt.API$ApiPhase.processScalaUnit(API.scala:46)
at xsbt.API$ApiPhase.processUnit(API.scala:37)
at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:33)
at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:33)
at scala.collection.Iterator$class.foreach(Iterator.scala:695)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1122)
at xsbt.API$ApiPhase.run(API.scala:33)
at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1307)
at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1280)
at scala.tools.nsc.Global$Run.compileSources(Global.scala:1274)
at scala.tools.nsc.Global$Run.compile(Global.scala:1404)
at xsbt.CompilerInterface.run(CompilerInterface.scala:106)
at scala.tools.eclipse.buildmanager.sbtintegration.ScalaSbtCompiler.compile(ScalaSbtCompiler.scala:35)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile$$anonfun$9.compileScala$1(AnalysisCompile.scala:137)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile$$anonfun$9.apply(AnalysisCompile.scala:175)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile$$anonfun$9.apply(AnalysisCompile.scala:112)
at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:21)
at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:19)
at sbt.inc.Incremental$.cycle(Incremental.scala:33)
at sbt.inc.Incremental$.compile(Incremental.scala:20)
at sbt.inc.IncrementalCompile$.apply(Compile.scala:17)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile.doCompile(AnalysisCompile.scala:193)
at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.runCompiler(EclipseSbtBuildManager.scala:369)
at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.update(EclipseSbtBuildManager.scala:331)
at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.build(EclipseSbtBuildManager.scala:433)
at scala.tools.eclipse.ScalaProject.build(ScalaProject.scala:718)
at scala.tools.eclipse.ScalaBuilder.build(ScalaBuilder.scala:114)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:513)
at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:432)
at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:305)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#417](https://github.com/sbt/sbt/issues/417) for the full issue and to comment.
