### ISSUE TITLE
IO.copyFile fails with larger files on Windows

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#491]
```
java.io.IOException: Map failed
        at sun.nio.ch.FileChannelImpl.map(Unknown Source)
        at sun.nio.ch.FileChannelImpl.transferFromFileChannel(Unknown Source)
        at sun.nio.ch.FileChannelImpl.transferFrom(Unknown Source)
        at sbt.IO$$anonfun$copyFile$3$$anonfun$apply$3.apply(IO.scala:458)
        at sbt.IO$$anonfun$copyFile$3$$anonfun$apply$3.apply(IO.scala:457)
        at sbt.Using.apply(Using.scala:25)
        at sbt.IO$$anonfun$copyFile$3.apply(IO.scala:457)
        at sbt.IO$$anonfun$copyFile$3.apply(IO.scala:456)
        at sbt.Using.apply(Using.scala:25)
        at sbt.IO$.copyFile(IO.scala:456)
        at build$$anonfun$copyToUnmanagedJar$2.apply(build.scala:326)
```

Seems like:

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4469299

Possible workaround:

http://dzone.com/snippets/java-filecopy-using-nio

Or by avoiding NIO on the Windows platform for file copying.

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#491](https://github.com/sbt/sbt/issues/491) for the full issue and to comment.
