### ISSUE TITLE
sbt console fails to load terminal - Invalid terminal type: jline.UnixTerminal

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#562]
I'm running "sbt console" using 0.12.0 under cygwin on windows with scala 2.9.2, jdk 1.6.0_25.

I'm using the shell script supplied as part of the MSI, and TERM=xterm.

I get this output, and the terminal is fairly non functional (no local echo, ^D doesn't exit).

<code>$ sbt console
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-sbt#boot-jna
        confs: [default]
        1 artifacts copied, 0 already retrieved (838kB/125ms)
Getting org.scala-sbt sbt 0.12.0 ...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        40 artifacts copied, 0 already retrieved (8158kB/5419ms)
Getting Scala 2.9.2 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        4 artifacts copied, 0 already retrieved (20090kB/3389ms)
[info] Loading project definition from D:\workspace\scalaz-example-sbt\project
[info] Set current project to scalaz-example-sbt (in build file:/D:/workspace/scalaz-example-sbt/)
[info] Starting scala interpreter...
[info]
[ERROR] Failed to construct terminal; falling back to unsupportedjava.lang.IllegalArgumentException: Invalid terminal type: jline.UnixTerminal
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:83)
        at scala.tools.jline.TerminalFactory.get(TerminalFactory.java:154)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:87)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:134)
        at scala.tools.nsc.interpreter.JLineReader$JLineConsoleReader.<init>(JLineReader.scala:42)
        at scala.tools.nsc.interpreter.JLineReader.<init>(JLineReader.scala:21)
        at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:777)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:796)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:851)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:73)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:64)
        at sbt.Console.console0$1(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
        at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
        at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
Caused by: java.lang.ClassCastException: jline.UnixTerminal cannot be cast to scala.tools.jline.Terminal
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:80)
        ... 19 more
Welcome to Scala version 2.9.2 (Java HotSpot(TM) Client VM, Java 1.6.0_25).
Type in expressions to have them evaluated.
Type :help for more information.
scala>
</code>

This seems to be an incompatibility between a jline.jar containing scala.tools.jline at ~/.sbt/boot/scala-2.9.2/lib/jline.jar and one containing plain ole jline at ~/.sbt/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.0/jline-1.0.jar.

If I delete the former, I get the same as issue #504.  If I wipe ~/.sbt/boot as mentioned in 504, sbt downloads it all again.

Any workaround gratefully received.

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#562](https://github.com/sbt/sbt/issues/562) for the full issue and to comment.
