### ISSUE TITLE
Crash: 'URI has an authority component' while processing dependencies

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#564]
I found this stack trace in my logs (using 0.13.0-SNAPSHOT):

```
java.lang.IllegalArgumentException: URI has an authority component
    at java.io.File.<init>(File.java:368)
    at sbt.IO$.urlAsFile(IO.scala:77)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$processDependency$1$1$$anonfun$apply$mcV$sp$1.apply(Analyze.scala:48)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$processDependency$1$1$$anonfun$apply$mcV$sp$1.apply(Analyze.scala:48)
    at scala.Option.foreach(Option.scala:197)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$processDependency$1$1.apply$mcV$sp(Analyze.scala:48)
    at sbt.classfile.Analyze$.sbt$classfile$Analyze$$trapAndLog(Analyze.scala:78)
    at sbt.classfile.Analyze$$anonfun$apply$9.processDependency$1(Analyze.scala:47)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$apply$12.apply(Analyze.scala:65)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$apply$12.apply(Analyze.scala:65)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:130)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:275)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:275)
    at sbt.classfile.Analyze$$anonfun$apply$9.apply(Analyze.scala:65)
    at sbt.classfile.Analyze$$anonfun$apply$9.apply(Analyze.scala:42)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:95)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:95)
    at scala.collection.Iterator$class.foreach(Iterator.scala:772)
    at scala.collection.mutable.HashTable$$anon$1.foreach(HashTable.scala:157)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:190)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:45)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:95)
    at sbt.classfile.Analyze$.apply(Analyze.scala:42)
```

The classpath contains UNC paths, like so:

`\\foo\dist\bar\sunjdk\1.6.0_31\exec\jre\lib\resources.jar;\\foo\dist\bar\sunjdk\1.6.0_31\exec\jre\lib\rt.jar;`

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#564](https://github.com/sbt/sbt/issues/564) for the full issue and to comment.
