### ISSUE TITLE
Building the 0.9 launcher fails on windows

### ISSUE THREAD

**Issue by harrah** [harrah/xsbt#9]
When I checkout the project and run the proguard command I get:

[info]    Interface / generate-source ...
java.lang.RuntimeException: {line 0} Invalid line, expected enum, class, or member definition
        at xsbt.api.DatatypeParser.error(DatatypeParser.scala:25)
        at xsbt.api.DatatypeParser$$anonfun$matchPattern$2.apply(DatatypeParser.scala:42)
        at xsbt.api.DatatypeParser$$anonfun$matchPattern$2.apply(DatatypeParser.scala:42)
        at scala.Option.getOrElse(Option.scala:104)
        at xsbt.api.DatatypeParser.matchPattern(DatatypeParser.scala:41)
        at xsbt.api.DatatypeParser.parseLine(DatatypeParser.scala:38)
        at xsbt.api.DatatypeParser$$anonfun$parseLines$1.apply(DatatypeParser.scala:34)
        at xsbt.api.DatatypeParser$$anonfun$parseLines$1.apply(DatatypeParser.scala:34)
        at scala.Function$$anonfun$tupled$1.apply(Function.scala:103)
        at scala.Function$$anonfun$tupled$1.apply(Function.scala:102)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)

Is there a place where I can download the launcher in the meantime?

Thanks.

**Comment by harrah** [comment]
**IMPORTANT** This project has moved to https://github.com/sbt/sbt.  This issue still exists to avoid dead links, but GitHub limitations prevent the original issue from being correctly preserved here.  Please see [sbt/sbt#9](https://github.com/sbt/sbt/issues/9) for the full issue and to comment.
